### PR TITLE
Greg

### PR DESCRIPTION
**Pull request by saynegrojas**
minimal css on the modal. This works on my comp but I'm wondering how it looks on you guys' comps.

### CODE REVIEW

**Comment by dhuan008** [comment]
Did you pull before pushing? we made some changes already.

**Comment by dhuan008** [comment]
Can you send a pic?

**Comment by dhuan008** [comment]
Capture

I don't think it really matches the theme, we want a blue semi transparent background with white text.

It does look alot better than before, However I think we already added the basic style.

**Comment by saynegrojas** [comment]
I pulled a bit after I got home. I agree it's not the same theme. I just wanted to put one out just in case none of us got to it. I re-did it but I'm too tired now. Here's what mine shows. 
Screen Shot 2019-06-15 at 3 50 13 AM

**Comment by saynegrojas** [comment]
still got to fix the position of the button but imma sleep now

**Comment by dhuan008** [comment]
Looks good! I added your changes into master but I'm not going to merge this branch because of merge conflicts.

**Pull request closed without merging**
